defaults:
  - model: animatediff
  - _self_

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

# Generation parameters
prompt: "a beautiful landscape"
num_frames: 32
width: 256
height: 256
